# Generated by Django 2.2.1 on 2019-07-04 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecastProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeatherForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('temp_unit', models.CharField(default='°C', max_length=2)),
                ('min_temp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_temp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('pop', models.PositiveSmallIntegerField(blank=True, help_text='Probability of precipitation in %.', null=True, verbose_name='POP')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.Location')),
            ],
            options={
                'ordering': ('-start_time',),
            },
        ),
        migrations.AddField(
            model_name='location',
            name='weather_forecast_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.WeatherForecastProvider'),
        ),
    ]
